baseURL = 'http://green.netescape.org/'
languageCode = 'en-us'
title = '#00FF00.LOG'
theme = 'smol'
copyright = 'Green'

# Parameters
[params]
    subtitle = "Is this what it's like to see the other side of the screen?"
    dateFmt = "2006-01-02 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "entries"
        name = "Entries"
        url = "/entries/"
        weight = 1 

#  [[menu.main]]
#        identifier = "categories"
#        name = "Categories"
#        url = "/categories/"
#        weight = 2 
#
#  [[menu.main]]
#        identifier = "tags"
#        name = "Tags"
#        url = "/tags/"
#        weight = 3

  [[menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/index.xml"
        weight = 4

# Footer
  [[menu.footer]]
        name = "NETeSCAPE"
        url = "https://netescape.org"
        weight = 1 

    [[menu.footer]]
        name = ".TXT"
        url = "https://txt.netescape.org"
        weight = 2 